ontrendclothing/ontrendclothing/urls.py
from django.contrib import admin
from django.urls import path
from product.views import productviews

urlpatterns = [

    path('', productviews.login),
    path('login', productviews.login),
    path('custLogin', productviews.custLogin),
    path('logout', productviews.logout),
    path('custLogout', productviews.custLogout),
    path('addproduct', productviews.addproduct),
    path('showproduct', productviews.showproduct),
    path('editproduct/<int:id>', productviews.editproduct),
    path('updateproduct/<int:id>', productviews.updateproduct),
    path('deleteproduct/<int:id>', productviews.deleteproduct),
    path('addtype', productviews.addtype),
    path('addvendor', productviews.addvendor),
    path('adduser', productviews.adduser),
    path('showuser', productviews.showuser),
    path('edituser/<int:id>', productviews.edituser),
    path('updateuser/<int:id>', productviews.updateuser),
    path('deleteuser/<int:id>', productviews.deleteuser),
    path('addcust', productviews.addcust),
    path('showcust', productviews.showcust),
    path('editcust/<int:id>', productviews.editcust),
    path('updatecust/<int:id>', productviews.updatecust),
    path('deletecust/<int:id>', productviews.deletecust),
    path('home', productviews.home),
    path('custhome', productviews.custhome),
    path('onlinestore', productviews.onlinestore),
    path('allproducts', productviews.allproducts),
    path('custallproducts', productviews.custallproducts),
    path('productdetails/<int:id>', productviews.productdetails),
    path('custproductdetails/<int:id>', productviews.custproductdetails),
    path('addreview', productviews.addreview),
    path('search', productviews.search),
    path('searchproduct', productviews.searchproduct),
    path('custsearchproduct', productviews.custsearchproduct),
    path('getsearchedproduct', productviews.getsearchedproduct),
    path('getcustsearchedproduct', productviews.getcustsearchedproduct),
    path('customize', productviews.customize),
    
]

ontrendclothing/product/models/productmodels.py
from django.db import models


class Product(models.Model):
    SKU              = models.AutoField(primary_key=True)
    title            = models.CharField(max_length=50)
    description      = models.TextField()
    price            = models.PositiveIntegerField(default = 0)
    featureImg       = models.ImageField(default="img.jpg", upload_to='images/')
    displayImg       = models.ImageField(default="img.jpg", upload_to='images/')
    displayImgFirst  = models.ImageField(default="img.jpg", upload_to='images/')
    displayImgSecond = models.ImageField(default="img.jpg", upload_to='images/')
    displayImgThird  = models.ImageField(default="img.jpg", upload_to='images/')
    xs               = models.PositiveIntegerField(default = 0)
    sm               = models.PositiveIntegerField(default = 0)
    md               = models.PositiveIntegerField(default = 0)
    lg               = models.PositiveIntegerField(default = 0)
    xl               = models.PositiveIntegerField(default = 0)
    xxl              = models.PositiveIntegerField(default = 0)
    xxxl             = models.PositiveIntegerField(default = 0)
    type             = models.ForeignKey('Type', on_delete=models.CASCADE, default = " ")
    vendor           = models.ForeignKey('Vendor', on_delete=models.CASCADE, default = " ")

    class Meta:
        db_table = "product"

    def __str__(self):
        return self.title

    def totalInventory(self):
        return self.xs+self.sm+self.md+self.lg+self.xl+self.xxl+self.xxxl

class Type(models.Model):
    type = models.CharField(max_length=50, primary_key=True, default=None)

    class Meta:
        db_table = "type"

    def __str__(self):
        return self.type

class Vendor(models.Model):
    vendor = models.CharField(max_length=50, primary_key=True, default=None)

    class Meta:
        db_table = "vendor"

    def __str__(self):
        return self.vendor

class User(models.Model):
    username   = models.CharField(max_length=30)
    first_name = models.CharField(max_length=30)
    last_name  = models.CharField(max_length=30)
    useremail  = models.EmailField()
    password   = models.CharField(max_length=50)
    isAdmin    = models.BooleanField(default=False)
    img        = models.ImageField(default="img.jpg", upload_to='images/')
    class Meta:
        db_table = "user"

        def __str__(self):
            return self.username

class Customer(models.Model):
    user       = models.CharField(max_length=30)
    first_name = models.CharField(max_length=30)
    last_name  = models.CharField(max_length=30)
    email      = models.EmailField()
    key        = models.CharField(max_length=50)
    img        = models.ImageField(default="img.jpg", upload_to='images/')
    class Meta:
        db_table = "customer"

        def __str__(self):
            return self.user


class Customize(models.Model):
    mainbanner          = models.ImageField(default="images/70550984_10157373051965535_3336865258831609856_n.jpg", upload_to='images/')
    menbanner           = models.ImageField(default="images/64514024_2171307086325281_2513036548014866432_n.jpg", upload_to='images/')
    womenbanner         = models.ImageField(default="images/66695107_2171307216325268_6767799174848053248_n.jpg", upload_to='images/')
    herotitle           = models.CharField(max_length=50, default="Stay home and")
    herosubtitle        = models.CharField(max_length=50, default="Shop online")
    herobtntitle        = models.CharField(max_length=50, default="All Products")
    ghostbtntitle       = models.CharField(max_length=50, default="Reviews")
    featureprodtitle    = models.CharField(max_length=50, default="Ontrend this summer")
    reviewsectiontitle  = models.CharField(max_length=50, default="Our customers get all Apparel from us.")
    class Meta:
        db_table = "customize"


        

class Review(models.Model):
    name = models.CharField(max_length=50)
    review = models.TextField()
    img = models.ImageField(default="hero.jpg", upload_to='images/')
    class Meta:
        db_table = "review"

ontrendclothing/product/forms/productforms.py
from django import forms
from product.models.productmodels import Product, Type, Vendor, User, Customer, Customize, Review

class ProductForm(forms.ModelForm):
    #productsize = forms.ModelChoiceField(queryset=Size.objects.all())
    class Meta:
        model = Product
        fields = ['title', 'description', 'price', 'featureImg', 'displayImg', 'displayImgFirst', 'displayImgSecond', 'displayImgThird', 'vendor', 'type', 'xs', 'sm', 'md', 'lg', 'xl', 'xxl', 'xxxl']

class TypeForm(forms.ModelForm):
    class Meta:
        model = Type
        fields = "__all__"


class VendorForm(forms.ModelForm):
    class Meta:
        model = Vendor
        fields = "__all__"

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = "__all__"


class CustomerForm(forms.ModelForm):
    key = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = Customer
        fields = ['user', 'first_name', 'last_name', 'email', 'key', 'img']



class CustomizeForm(forms.ModelForm):
    class Meta:
        model = Customize
        fields = "__all__"


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = "__all__"

ontrendclothing/product/views/productviews.py
from django.shortcuts import render, redirect
from product.models.productmodels import Product, Type, Vendor, User, Customer, Customize, Review
from product.forms.productforms import ProductForm, TypeForm, VendorForm, UserForm, CustomerForm, CustomizeForm, ReviewForm
from django.http import HttpResponse,JsonResponse
from product.authenticate import Authenticate
from django.db.models import Q 
from django.core.paginator import Paginator


'''
-------------------------------------------------------------
-----------User Login/logout---------------------------------
-------------------------------------------------------------
'''

def login(request):
    if request.method == "POST":
        request.session['username'] = request.POST['username']
        request.session['password'] = request.POST['password']
        try:
            user = User.objects.get(Q(username = request.POST.get('username')) & Q(password = request.POST.get('password'))) 
            if(user):
                request.session['id']= user.id
                request.session['isAdmin']= user.isAdmin
        except:
            pass
        return redirect('/showproduct')
    return render(request, 'login.html')


def logout(request):
    del request.session['username']
    del request.session['password']
    return redirect('/login')


'''
-------------------------------------------------------------
-----------Customer Login/Logout-----------------------------
-------------------------------------------------------------
'''


def custLogin(request):
    if request.method == "POST":
        request.session['user'] = request.POST['user']
        request.session['key'] = request.POST['key']
        try:
            cust = Customer.objects.get(Q(user = request.POST.get('user')) & Q(key = request.POST.get('key'))) 
            if(cust):
                request.session['custid']= cust.id
        except:
            pass
        return redirect('/custhome')
    return render(request, 'custlogin.html')


def custLogout(request):
    del request.session['user']
    del request.session['key']
    return redirect('/home')


'''
-------------------------------------------------------------
-----------Product add/update/delete----------------
-------------------------------------------------------------
'''

@Authenticate.valid_user
def addproduct(request):
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)
        typeform = TypeForm()
        print("entered post")
        if form.is_valid():
            print("is valid")
            form.save()
            return redirect('/showproduct')
    else:
        form = ProductForm()
        typeform = TypeForm()
        user = User.objects.get(id = request.session['id'])
    return render(request, 'newproduct.html', {'form':form, 'typeform': typeform, 'user':user})


def editproduct(request, id):
    if (request.session['username'] != "" ):
        vendors = Vendor.objects.all()
        types = Type.objects.all()
        products = Product.objects.get(SKU=id)
        return render(request, 'productedit.html', {'products':products, 'types':types, 'vendors':vendors})
    else:
        return redirect('/login')


def updateproduct(request, id):
    if (request.session['username'] != "" ):
        product = Product.objects.get(SKU=id)
        if request.method == "POST":
            form = ProductForm(request.POST, request.FILES, instance=product)
            if form.is_valid:
                form.save()
            return redirect('/showproduct')
        else:
            form = ProductForm()
        return render(request, 'productedit.html', {'form': form})
    else:
        return redirect('/login')


def deleteproduct(request, id):
    product = Product.objects.get(SKU = id)
    print("hi deleting")
    print(request.session['isAdmin'])
    if request.session['isAdmin'] == True:
        print("entered if in delete")
        product.delete()
    else:
        return redirect('/showproduct')
    return redirect('/showproduct')


@Authenticate.valid_user
def showproduct(request):
    limit = 5
    products = Product.objects.all().order_by('title')
    vendors = Vendor.objects.all()
    user = User.objects.get(id = request.session['id'])
    paginator = Paginator(products, limit)
    page =request.GET.get('page')
    products = paginator.get_page(page)
    
    return render(request, 'dashboard.html', {'products':products, 'vendors': vendors, 'user':user})


'''
-------------------------------------------------------------
-----------Product Type--------------------------------------
-------------------------------------------------------------
'''

@Authenticate.valid_user
def addtype(request):
    types = Type.objects.all()
    if request.method == 'POST':
        form = TypeForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/addproduct')
            except:
                pass
    else:
        form = TypeForm()
    return render(request, 'newtype.html', {'form':form, 'types': types})



@Authenticate.valid_user
def showTypes(request):
    types = Type.objects.all()
    return render(request, 'dashboard.html', {'types':types})


'''
-------------------------------------------------------------
-----------Product Vendor------------------------------------
-------------------------------------------------------------
'''

@Authenticate.valid_user
def addvendor(request):
    if request.method == 'POST':
        form = VendorForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/addproduct')
            except:
                pass
    else:
        form = VendorForm()
    return render(request, 'newvendor.html', {'form':form})



@Authenticate.valid_user
def showVendor(request):
    vendors = Vendor.objects.all()
    return render(request, 'newvendor.html', {'vendors':vendors})


'''
-------------------------------------------------------------
-----------User add/update/delete/show-----------------------
-------------------------------------------------------------
'''

def adduser(request):
    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                form.save()
                return redirect('/login')
            except:
                pass
    else:
        form = UserForm()
    return render(request, 'register.html', {'form':form})


def edituser(request, id):
    user = User.objects.get(id = id)
    adminuser = User.objects.get(id=request.session['id'])
    if request.session['isAdmin'] == True or request.session['id']==user.id:
        return render(request, 'updateuser.html', {'user':user, 'adminuser':adminuser})
    else:
        return redirect('/showuser')



def updateuser(request, id):
    user = User.objects.get(id=id)
    if request.method == "POST":
        form = UserForm(request.POST, request.FILES, instance = user)
        if form.is_valid:
            form.save()
        return redirect('/showproduct')
    else:
        form = UserForm()       
    return render(request, 'updateuser.html', {'user':user})


def deleteuser(request, id):
    user = User.objects.get(id = id)
    if request.session['isAdmin'] == True or request.session['id']==user.id:
        user.delete()
    else:
        return redirect('/showproduct')
    return redirect('/showuser')


@Authenticate.valid_user
def showuser(request):
    limit = 1;
    users = User.objects.all()
    user = User.objects.get(id = request.session['id'])
    paginator = Paginator(users, limit)
    page =request.GET.get('page')
    users = paginator.get_page(page)
    return render(request, 'dashboarduser.html', {'users':users, 'user':user})



'''
-------------------------------------------------------------
-----------Customer add/update/delete/show-----------------------
-------------------------------------------------------------
'''

def addcust(request):
    if request.method == 'POST':
        custform = CustomerForm(request.POST, request.FILES)
        if custform.is_valid():
            try:
                custform.save()
                return redirect('/custLogin')
            except:
                pass
    else:
        custform = CustomerForm()
    return render(request, 'custadd.html', {'custform':custform})
    

def editcust(request, id):
    cust = Customer.objects.get(id = id)
    return render(request, 'custupdate.html', {'cust':cust})


def updatecust(request, id):
    cust = Customer.objects.get(id=id)
    if request.method == "POST":
        form = CustomerForm(request.POST, request.FILES, instance = cust)
        if form.is_valid:
            form.save()
        return redirect('/custhome')
    else:
        form = CustomerForm()       
    return render(request, 'custupdate.html', {'cust':cust})


def deletecust(request, id):
    cust = Customer.objects.get(id = id)
    print("hi deleting")
    if request.session['custid'] == cust.id:
        print("entered if in delete")
        cust.delete()
    else:
        return redirect('/custhome')
    return redirect('/home')


@Authenticate.valid_user
def showcust(request):
    limit = 1;
    custs = Customer.objects.all()
    user = User.objects.get(id = request.session['id'])
    paginator = Paginator(custs, limit)
    page =request.GET.get('page')
    custs = paginator.get_page(page)
    return render(request, 'dashboardcust.html', {'custs':custs, 'user':user})


'''
-------------------------------------------------------------
-----------Customer Reviews about product--------------------
-------------------------------------------------------------
'''

def addreview(request):
    if request.method == 'POST':
        revform = ReviewForm(request.POST, request.FILES)
        if revform.is_valid():
            try:
                revform.save()
                return redirect('/home')
            except:

ontrendclothing/product/templates/custlogin.html
{% extends "layout-frontend.html" %}
{% block class%} class="sticky"{% endblock %}
{% block content %}
<section class="section-form">
    <div class="row">
        <h2>Login to see your customize collection!</h2>
    </div>



    <div class="row">
        <form method="post" action="/custLogin" class="contact-form">
            {% csrf_token%}

              <div class="row">
                <div class="col span-1-of-3">
                    <label for="Username">Username</label>
                </div>
                <div class="col span-2-of-3">
                    <input type="text" name="user" required="" maxlength="30" id="id_user">
                </div>
            </div>
            <div class="row">
                <div class="col span-1-of-3">
                    <label for="Password">Password</label>
                </div>
                <div class="col span-2-of-3">
                    <input type="password" name="key"  maxlength="30" required="" id="id_key">
                </div>
            </div>


            <div class="row">
                <div class="col span-1-of-3">
                    <label>&nbsp;</label>
                </div>
                <div class="col span-2-of-3">
                    <input type="submit" value="Get in!">
                </div>
            </div>

        </form>
        
    </div>
</section>
{% endblock %}
        

ontrendclothing/product/templates/custupdate.html
{% extends "layout-frontend.html" %}
    {% block class%} class="sticky"{% endblock %}
    {% block content %}




    <!-- Search form -->

<!-- Search form -->

{% load static %}

<section class="section-form">
    <div class="row">
        <h2>Update your profile here!</h2>
    </div>



    <div class="row">
        <form method="post" action="/updatecust/{{cust.id}}" class="contact-form" enctype="multipart/form-data">
            {% csrf_token%}
            <div class="row">
                <div class="col span-1-of-3">
                    <label for="firstname">First Name</label>
                </div>
                <div class="col span-2-of-3">
                    <input type="text" name="first_name" maxlength="30" required="" id="id_first_name" value="{{cust.first_name}}">
                </div>
            </div>
            <div class="row">
                <div class="col span-1-of-3">
                    <label for="lastname">Last Name</label>
                </div>
                <div class="col span-2-of-3">
                    <input type="text" name="last_name" maxlength="30" required="" id="id_last_name" value="{{cust.last_name}}">
                </div>
            </div>
            <div class="row">
                <div class="col span-1-of-3">
                    <label for="username">Username</label>

                </div>
                <div class="col span-2-of-3">
                    <input type="text" name="user" maxlength="30" required="" id="id_user" value="{{cust.user}}">
                </div>
            </div>
            <div class="row">
                <div class="col span-1-of-3">
                    <label for="email">Email</label>
                </div>
                <div class="col span-2-of-3">
                    <input type="email" name="email" maxlength="254" required="" id="id_email" value="{{cust.email}}">
                </div>
            </div>
            <div class="row">
                <div class="col span-1-of-3">
                    <label for="password">Password</label>
                </div>
                <div class="col span-2-of-3">
                    <input type="password" name="key" required="" id="id_key" value="{{cust.key}}">
                </div>
            </div>
            <div class="row">
                <div class="col span-1-of-3">
                    <label for="profile-pic">Profile Picture</label>
                </div>
                <div class="col span-2-of-3">
                    <img src="{% static '/media/' %}{{cust.img}}" alt="profile picture" width="100" height="100">
                </div>
            </div>
            <div class="row">
                <div class="col span-1-of-3">
                    <label for="profile-pic">Profile Picture</label>
                </div>
                <div class="col span-2-of-3">
                    <input type="file" name="img" accept="image/*" id="id_img">
                </div>
            </div> 
            <div class="row">
                <div class="col span-1-of-3">
                    <label>&nbsp;</label>
                </div>
                <div class="col span-2-of-3">
                    <input type="submit" value="Send it!">
                    <div class="custom-btn-del">
                        <a href="/deletecust/{{cust.id}}">Erase it!</a>
                    </div>
                    
                </div>
            </div>

        </form>
        
    </div>
</section>

{% endblock %}

ontrendclothing/product/templates/productedit.html
{% extends "layout.html" %}
{% block title%}Dashboard{% endblock %}
{% block head%}Dashboard{% endblock %}
{% block content %}



<form method="POST" class="post-form" action="/updateproduct/{{products.SKU}}" enctype="multipart/form-data">
	{% csrf_token%}
  {% load static %}
	<div class="container">
		<br>
		<div class="form-group row">
			<label class="col-sm-4 col-form-label"></label>
			<div class="col-sm-8">
				<h3>Enter Details</h3>
			</div>
		</div>
		<div class="form-group row">
			<label class="col-sm-4 col-form-label">Title:</label>
			<div class="col-sm-8 product-title">
				<input type="text" name="title" maxlength="50" required="" id="id_title" value="{{products.title}}">
			</div>
		</div>
		<div class="form-group row">
			<label class="col-sm-4 col-form-label">Description</label>
			<div class="col-sm-8 product-description">
				<textarea name="description" cols="40" rows="10" required="" id="id_description">{{products.description}}</textarea>
			</div>
		</div>
		<div class="form-group row">
			<label class="col-sm-4 col-form-label">Price</label>
			<div class="col-sm-8 product-price">
				<input type="number" name="price" min="0" required="" id="id_price" value="{{products.price}}">
			</div>
		</div>
		<div class="form-group row">
			<label class="col-sm-4 col-form-label">Featured Image:</label>
			<div class="col-sm-8 product-img">
				<input type="file" name="featureImg" accept="image/*" id="id_featureImg" >
				<img class="rounded product-thumbnail-edit" src="{% static '/media/' %}{{products.featureImg}}" alt="Featured Image">
			</div>
		</div>
		<div class="form-group row">
			<label class="col-sm-4 col-form-label">Display Images:</label>
			<div class="col-sm-8 product-img">
				<input type="file" name="displayImg" accept="image/*" id="id_displayImg">
				<img class="rounded  product-thumbnail-edit" src="{% static '/media/' %}{{products.displayImg}}" alt="Display Image">

			</div>
		</div>
		<div class="form-group row">
			<label class="col-sm-4 col-form-label">Display Images:</label>
			<div class="col-sm-8 product-img">
				<input type="file" name="displayImgFirst" accept="image/*" id="id_displayImgFirst">
				<img class="rounded  product-thumbnail-edit" src="{% static '/media/' %}{{products.displayImgFirst}}" alt="Display Image">

			</div>
		</div>
		<div class="form-group row">
			<label class="col-sm-4 col-form-label">Display Images:</label>
			<div class="col-sm-8 product-img">
				<input type="file" name="displayImgSecond" accept="image/*" id="id_displayImgSecond">
				<img class="rounded product-thumbnail-edit" src="{% static '/media/' %}{{products.displayImgSecond}}" alt="Display Image">

			</div>
		</div>
		<div class="form-group row">
			<label class="col-sm-4 col-form-label">Display Images:</label>
			<div class="col-sm-8 product-img">
				<input type="file" name="displayImgThird" accept="image/*" id="id_displayImgThird">
				<img class="rounded product-thumbnail-edit" src="{% static '/media/' %}{{products.displayImgThird}}" alt="Display Image">

			</div>
		</div>
		<div class="form-group row">
			<label class="col-sm-4 col-form-label">Vendor</label>
			<div class="col-sm-8 product-vendor">
				<select name="vendor" id="id_vendor">
					{% for vendor in vendors %}
				  <option value="{{vendor.vendor}}">{{vendor.vendor}}</option>
					{% endfor %}
				</select>
			</div>
		</div>
		<div class="form-group row">
			<label class="col-sm-4 col-form-label">Product Type:</label>
			<div class="col-sm-8 product-type">
				<select name="type" id="id_type">
					{% for type in types %}
					  <option value={{type.type}}>{{type.type}}</option>
					{% endfor %}
				</select>
			</div>
		</div>
		<div class="form-group row">
			<label class="col-sm-4 col-form-label"></label>
			<div class="col-sm-8">
				<h3>Inventories</h3>
			</div>
		</div>
		<div class="form-group row">
			<label class="col-sm-4 col-form-label">XS:</label>
			<div class="col-sm-8 product-inventory">
				<input type="number" name="xs" min="0" required="" id="id_xs" value="{{products.xs}}">
			</div>
		</div>
		<div class="form-group row">
			<label class="col-sm-4 col-form-label">SM:</label>
			<div class="col-sm-8 product-inventory">
				<input type="number" name="sm" min="0" required="" id="id_sm" value="{{products.sm}}">
			</div>
		</div>
		<div class="form-group row">
			<label class="col-sm-4 col-form-label">MD:</label>
			<div class="col-sm-8 product-inventory">
				<input type="number" name="md" min="0" required="" id="id_md" value="{{products.md}}">
			</div>
		</div>
		<div class="form-group row">
			<label class="col-sm-4 col-form-label">LG:</label>
			<div class="col-sm-8 product-inventory">
				<input type="number" name="lg" min="0" required="" id="id_lg" value="{{products.lg}}">
			</div>
		</div>
		<div class="form-group row">
			<label class="col-sm-4 col-form-label">XL:</label>
			<div class="col-sm-8 product-inventory">
				<input type="number" name="xl" min="0" required="" id="id_xl" value="{{products.xl}}">
			</div>
		</div>
		<div class="form-group row">
			<label class="col-sm-4 col-form-label">XXL:</label>
			<div class="col-sm-8 product-inventory">
				<input type="number" name="xxl" min="0" required="" id="id_xxl" value="{{products.xxl}}">
			</div>
		</div>
		<div class="form-group row">
			<label class="col-sm-4 col-form-label">XXXL:</label>
			<div class="col-sm-8 product-inventory">
				<input type="number" name="xxxl" min="0" required="" id="id_xxxl" value="{{products.xxxl}}">
			</div>
		</div>
		<div class="form-group row">
			<label class="col-sm-4 col-form-label"></label>
			<div class="col-sm-8 product-update">
				<button type="submit" class="btn btn-primary">Update</button>
			</div>
		</div>
	</div>
</form>
<div class="row">
	<div class="col-sm-4">

	</div>
	<div class="col-sm-4">
		<a class="btn btn-danger" href="/deleteproduct/{{products.SKU}}">Delete</a>
	</div>
</div>
{% block newtype %}

{% endblock %}


{% endblock content %}

ontrendclothing/product/templates/userupdate.html
{% extends "layout-frontend.html" %}
    {% block class%} class="sticky"{% endblock %}
    {% block content %}





    
     <section class="section-form">
        <div class="row">
            <h2>We're happy to hear from you</h2>
        </div>



        <div class="row">
            <form method="post" action="/userupdate/{{user.id}}" class="contact-form" enctype="multipart/form-data">
                {% csrf_token%}
                <div class="row">
                    <div class="col span-1-of-3">
                        <label for="firstname">First Name</label>
                    </div>
                    <div class="col span-2-of-3">
                        <input type="text" name="first_name" maxlength="30" required="" id="id_first_name" value="{{user.first_name}}">
                    </div>
                </div>
                <div class="row">
                    <div class="col span-1-of-3">
                        <label for="lastname">Last Name</label>
                    </div>
                    <div class="col span-2-of-3">
                        <input type="text" name="last_name" maxlength="30" required="" id="id_last_name" value="{{user.last_name}}">
                    </div>
                </div>
                <div class="row">
                    <div class="col span-1-of-3">
                        <label for="username">Username</label>
                    </div>
                    <div class="col span-2-of-3">
                        <input type="text" name="username" maxlength="30" required="" id="id_username" value="{{user.username}}">
                    </div>
                </div>
                <div class="row">
                    <div class="col span-1-of-3">
                        <label for="email">Email</label>
                    </div>
                    <div class="col span-2-of-3">
                        <input type="email" name="useremail" maxlength="254" required="" id="id_useremail" value="{{user.useremail}}">
                    </div>
                </div>
                <div class="row">
                    <div class="col span-1-of-3">
                        <label for="password">Password</label>
                    </div>
                    <div class="col span-2-of-3">
                        <input type="password" name="password" required="" id="id_password" value="{{user.password}}">
                    </div>
                </div>
                <div class="row">
                    <div class="col span-1-of-3">
                        <label for="profile-pic">Profile Picture</label>
                    </div>
                    <div class="col span-2-of-3">
                        <input type="file" name="img" accept="image/*" id="id_img">
                    </div>
                </div> 

                <div class="row">
                    <div class="col span-1-of-3">
                        <label>&nbsp;</label>
                    </div>
                    <div class="col span-2-of-3">
                        <input type="submit" value="Send it!">
                    </div>
                </div>

            </form>
            
        </div>
    </section>

     {% endblock %}